# name: Project CI

# on:
#   push:
#     branches-ignore:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   python-security-ci:
#     uses: tokyoghoul212/ci-workflow/.github/workflows/python-security-ci.yml@main
#     with:
#       run_tests: true
#       run_sonar: true
#       run_snyk: true
#     secrets:
#       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

name: Project CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-security-ci:
    uses: tokyoghoul212/ci-workflow/.github/workflows/python-security-ci.yml@main
    with:
      python_version: "3.12"
      working_directory: "."
      requirements_file: "requirements.txt"

      run_tests: true
      test_command: "pytest -q"

      run_sonar: true
      sonar_args: ""

      run_snyk: true
      snyk_args: "--severity-threshold=high"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
